# -*- coding: utf-8 -*-
"""
Embed rules/forms_master.json into index.html, replacing whatever FORMS_MASTER
is already there. Run after rules/build_forms.py.

    python rules/build_forms.py && python rules/embed_forms.py
"""
import io, json, sys

PATH = 'index.html'
DROP_IF_EMPTY = ('aliases', 'referencedBy', 'triggers', 'steps', 'purpose',
                 'purposeFrom', 'description', 'whenRequired', 'timeline', 'section',
                 'penalty', 'portal', 'lastAmended', 'filingStatus', 'linked',
                 'notes', 'statusNote', 'frequency', 'signedBy', 'ruleId', 'needsReview')

HEADER = (
    '// Forms & filings master. Generated by rules/build_forms.py — do not hand-edit\n'
    '// here; edit the source sheets and rebuild, or the next build silently reverts it.\n'
    '// `forms` are currently valid. `withdrawn` are kept out of the working list but\n'
    '// still searchable, so an old checklist item resolves to "omitted" rather than\n'
    '// to silence, which is the failure mode that gets a dead form filed.\n'
    'var FORMS_MASTER = ')


def slim(rec):
    r = {}
    for k, v in rec.items():
        if k in DROP_IF_EMPTY and not v:
            continue
        if k == 'triggers':
            v = [{kk: vv for kk, vv in t.items() if kk != 'appliesTo' and vv} for t in v]
        r[k] = v
    return r


def main():
    data = json.load(io.open('rules/forms_master.json', encoding='utf-8'))
    payload = {'forms': [slim(f) for f in data['forms']],
               'withdrawn': [slim(f) for f in data['withdrawn']]}
    blob = json.dumps(payload, ensure_ascii=False, separators=(',', ':'))

    src = io.open(PATH, encoding='utf-8', newline='').read()
    i = src.find(HEADER)
    if i == -1:
        sys.exit('!! FORMS_MASTER block not found in %s — nothing written' % PATH)
    j = src.index('{', i)
    depth, k = 0, j
    while k < len(src):
        if src[k] == '{':
            depth += 1
        elif src[k] == '}':
            depth -= 1
            if depth == 0:
                break
        k += 1
    end = k + 1
    while end < len(src) and src[end] in ';':
        end += 1

    src = src[:i] + HEADER + blob + ';' + src[end:]
    io.open(PATH, 'w', encoding='utf-8', newline='').write(src)
    print('embedded %d active + %d withdrawn (%d KB)'
          % (len(payload['forms']), len(payload['withdrawn']), len(blob) // 1024))


if __name__ == '__main__':
    main()
